# Generated by Django 4.1.11 on 2023-09-30 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='fraudesAnalysis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_type', models.CharField(choices=[('deposit', 'deposit'), ('sacar', 'sacar'), ('pagar', 'pagar'), ('transferir', 'transferir')], max_length=20)),
                ('amount', models.FloatField()),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('FINISHED', 'FINISHED')], max_length=20)),
                ('fraudes_score', models.FloatField()),
                ('deny_reason', models.CharField(max_length=200)),
                ('cliente_id', models.CharField(max_length=20)),
                ('session_id', models.CharField(max_length=20)),
            ],
        ),
    ]
